# Don't change this version, this version is buildspec.yml file's version
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<REPO>
      - aws ecr get-login-password --region <REGION> | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${ENVIRONMENT}-${COMMIT_HASH}-$(date +%Y%m%d%H%M%S)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f ci/Dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definition file...
      - printf '[{"name":"nestjs-starter","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - 'imagedefinitions.json'

cache:
  paths:
    - /root/.npm/**/*
    - /root/.cache/yarn/**/*
