version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no

reports:
  jest_reports:
    files:
      - 'junit.xml'
    file-format: JUNITXML
    base-directory: '.'

cache:
  paths:
    - node_modules
