apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-starter
  template:
    metadata:
      labels:
        app: nestjs-starter
    spec:
      containers:
        - name: nestjs-starter-server
          image: nestjs-starter_server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: nestjs-secret
