apiVersion: v1
kind: Service
metadata:
  name: nestjs-starter-service
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31230
