apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  labels:
    app: nestjs-starter
spec:
  type: LoadBalancer
  selector:
    app: nestjs-starter
  ports:
    - port: 80
      targetPort: 3000