apiVersion: v1
kind: Service
metadata:
  name: starter-service
  labels:
    app: server
    service: api
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 32230
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800